# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='权限名称')),
                ('desc', models.TextField(verbose_name='权限说明')),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='会员名称')),
                ('level', models.IntegerField(verbose_name='会员等级')),
            ],
        ),
        migrations.CreateModel(
            name='VipPermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.IntegerField(verbose_name='会员id')),
                ('perm_id', models.IntegerField(verbose_name='权限 id')),
            ],
        ),
        migrations.CreateModel(
            name='VipProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.IntegerField(verbose_name='对应的 VIP 的ID')),
                ('price', models.FloatField(verbose_name='价格')),
                ('days', models.IntegerField(verbose_name='会员天数')),
            ],
        ),
    ]
