# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者ID')),
                ('sid', models.IntegerField(verbose_name='被滑动者ID')),
                ('stype', models.IntegerField(choices=[('superlike', '上滑'), ('like', '右滑'), ('dislike', '左滑')], max_length=16, verbose_name='滑动类型')),
                ('stime', models.DateTimeField(verbose_name='滑动时间')),
            ],
        ),
    ]
