# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiped',
            name='stype',
            field=models.CharField(choices=[('superlike', '上滑'), ('like', '右滑'), ('dislike', '左滑')], max_length=16, verbose_name='滑动类型'),
        ),
    ]
