# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191025_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=16, verbose_name='匹配的性别'),
        ),
    ]
