# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191027_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_end_date',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name='会员结束时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1, verbose_name='VIP 的 ID'),
        ),
    ]
